// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmJd0KcxYVXpBV-gOnabrHmSIHm2mMIP8',
    appId: '1:576142432657:web:8e87df21b08834cad4e230',
    messagingSenderId: '576142432657',
    projectId: 'midnightpulse-d5f4d',
    authDomain: 'midnightpulse-d5f4d.firebaseapp.com',
    storageBucket: 'midnightpulse-d5f4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlm_Nf533r5oXFcQc40VUUIotkOKvXMI',
    appId: '1:576142432657:android:454da542b5bdf31fd4e230',
    messagingSenderId: '576142432657',
    projectId: 'midnightpulse-d5f4d',
    storageBucket: 'midnightpulse-d5f4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7SapJRhgJaAWvPVWbBwn2TdLkUC1cijk',
    appId: '1:576142432657:ios:0f13ba191b983a8fd4e230',
    messagingSenderId: '576142432657',
    projectId: 'midnightpulse-d5f4d',
    storageBucket: 'midnightpulse-d5f4d.firebasestorage.app',
    iosBundleId: 'com.example.midnightPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7SapJRhgJaAWvPVWbBwn2TdLkUC1cijk',
    appId: '1:576142432657:ios:0f13ba191b983a8fd4e230',
    messagingSenderId: '576142432657',
    projectId: 'midnightpulse-d5f4d',
    storageBucket: 'midnightpulse-d5f4d.firebasestorage.app',
    iosBundleId: 'com.example.midnightPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmJd0KcxYVXpBV-gOnabrHmSIHm2mMIP8',
    appId: '1:576142432657:web:513cf0923aa78123d4e230',
    messagingSenderId: '576142432657',
    projectId: 'midnightpulse-d5f4d',
    authDomain: 'midnightpulse-d5f4d.firebaseapp.com',
    storageBucket: 'midnightpulse-d5f4d.firebasestorage.app',
  );
}
